name: Publish project to Maven repository
# publish on commit to main branch
on:
  push:
    branches: [ main, ci ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build publishAllPublicationsToAgsmvnsnapshotsRepository
        env:
          ORG_GRADLE_PROJECT_agsmvnsnapshotsUsername: ${{ secrets.MAVEN_NAME }} # token name
          ORG_GRADLE_PROJECT_agsmvnsnapshotsPassword: ${{ secrets.MAVEN_SECRET }} # token secret (password)