name: Publish project to Maven repository
# publish on commit to main branch
on:
  push:
    branches: [ main, ci ]
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: |
            if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
                ./gradlew build publishAllPublicationsToAgsmvnsnapshotsRepository
            else
                ./gradlew compileKotlinIosArm64 \
                  compileKotlinIosX64 \
                  compileKotlinMacosArm64 \
                  compileKotlinMacosX64 \
                  compileTestKotlinIosArm64 \
                  compileTestKotlinIosX64 \
                  compileTestKotlinMacosArm64 \
                  compileTestKotlinMacosX64 \
                  publishIosArm64PublicationToAgsmvnsnapshotsRepository \
                  publishIosX64PublicationToAgsmvnsnapshotsRepository \
                  publishMacosArm64PublicationToAgsmvnsnapshotsRepository \
                  publishMacosX64PublicationToAgsmvnsnapshotsRepository
            fi
        env:
          ORG_GRADLE_PROJECT_agsmvnsnapshotsUsername: ${{ secrets.MAVEN_NAME }} # token name
          ORG_GRADLE_PROJECT_agsmvnsnapshotsPassword: ${{ secrets.MAVEN_SECRET }} # token secret (password)